source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '11.0'

target 'LocationManager_Example' do
  pod 'LocationManager', :path => '../'
  pod 'PromiseKit', '~> 6.11'
  pod 'SwiftLint'
end

target 'LocationManager_Tests' do
  pod 'LocationManager', :path => '../'
end
