source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LocationManager_Example', :exclusive => true do
  pod 'LocationManager', :path => '../'
end

target 'LocationManager_Tests', :exclusive => true do
  pod 'LocationManager', :path => '../'

  pod 'FBSnapshotTestCase'
end
